version: '3.8'
networks:
  product:
services:
  product-service:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 5003:5003
    networks:
      - product
    volumes:
      - ./src/log:/usr/src/app/src/log
    restart: unless-stopped
  promtail:
    image: grafana/promtail
    volumes:
      - ./src/log:/var/product
      - ./promtail:/etc/promtail
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - product
